apiVersion: v1
kind: Service
metadata:
  name: mockstorage-service
  labels:
    app: mockstorage
spec:
  type: ClusterIP
  selector:
    app: mockstorage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080